# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intelligent_whellchair.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_intelligentwheelchair(object):
    def setupUi(self, intelligentwheelchair):
        intelligentwheelchair.setObjectName("intelligentwheelchair")
        intelligentwheelchair.resize(804, 623)
        intelligentwheelchair.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/1/bitbug_favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        intelligentwheelchair.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(intelligentwheelchair)
        self.centralwidget.setObjectName("centralwidget")
        self.begin = QtWidgets.QPushButton(self.centralwidget)
        self.begin.setGeometry(QtCore.QRect(620, 420, 151, 131))
        self.begin.setStyleSheet("QPushButton{background-color: rgb(238, 241, 248);\n"
"font: 24pt \"Adobe Arabic\";\n"
"border:2px outset #adadad;}\n"
"QPushButton::hover{\n"
"background-color:rgba(100,255,100,100);\n"
"border-color:rgba(255,255,255,200);\n"
"}  \n"
"QPushButton::pressed{\n"
"background-color: rgb(238, 241, 248);\n"
"font: 24pt \"Adobe Arabic\";\n"
"/*border:2px inset #656565;*/\n"
"border-top:2px inset #656565;\n"
"border-left:2px inset #656565;\n"
"border-bottom:2px inset #ffffff;\n"
"border-right:2px inset #ffffff;}")
        self.begin.setObjectName("begin")
        self.face = QtWidgets.QLabel(self.centralwidget)

        self.face.setFrameShape(QtWidgets.QFrame.Box)
        self.face.setFrameShadow(QtWidgets.QFrame.Raised)
        self.face.setLineWidth(5)
        # self.face.setStyleSheet('background-color: rgb(255, 0, 0)')

        self.face.setGeometry(QtCore.QRect(50, 320, 261, 211))
        # self.face.setStyleSheet("background-color: rgb(246, 192, 255);")
        self.face.setText("")
        self.face.setObjectName("face")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 80, 331, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stop = QtWidgets.QLabel(self.layoutWidget)
        self.stop.setStyleSheet("\n"
"border-image: url(:/1/Desktop/forword11.png);")
        self.stop.setText("")
        self.stop.setScaledContents(False)
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 1, 1, 1, 1)
        self.right = QtWidgets.QLabel(self.layoutWidget)
        self.right.setStyleSheet("border-image: url(:/1/Desktop/right1.png);")
        self.right.setText("")
        self.right.setScaledContents(False)
        self.right.setObjectName("right")
        self.gridLayout.addWidget(self.right, 1, 2, 1, 1)
        self.left = QtWidgets.QLabel(self.layoutWidget)
        self.left.setStyleSheet("border-image: url(:/1/Desktop/left1.png);")
        self.left.setText("")
        self.left.setScaledContents(False)
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 1, 0, 1, 1)
        self.up = QtWidgets.QLabel(self.layoutWidget)
        self.up.setStyleSheet("border-image: url(:/1/Desktop/up1.png);")
        self.up.setText("")
        self.up.setScaledContents(False)
        self.up.setObjectName("up")
        self.gridLayout.addWidget(self.up, 0, 1, 1, 1)
        self.eye = QtWidgets.QLabel(self.centralwidget)

        self.eye.setFrameShape(QtWidgets.QFrame.Box)
        self.eye.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eye.setLineWidth(5)

        self.eye.setGeometry(QtCore.QRect(50, 150, 261, 101))
        # self.eye.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.eye.setText("")
        #self.eye.setTextFormat(QtCore.Qt.MarkdownText)
        self.eye.setObjectName("eye")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(52, 120, 72, 21))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)

        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(1)

        self.label_3.setGeometry(QtCore.QRect(30, 90, 301, 481))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 261, 41))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 24px;\n"
"    color: #BDC8E2;\n"
"    background-color: #2E3648;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(51, 290, 72, 21))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(390, 20, 331, 41))
        self.label_7.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 24px;\n"
"    color: #BDC8E2;\n"
"    background-color: #2E3648;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(370, 370, 211, 183))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.camera_word = QtWidgets.QLineEdit(self.splitter)
        self.camera_word.setMaximumSize(QtCore.QSize(90, 16777215))
        self.camera_word.setReadOnly(True)
        self.camera_word.setObjectName("camera_word")
        self.comboBox_camera = QtWidgets.QComboBox(self.splitter)
        self.comboBox_camera.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.comboBox_camera.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboBox_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_camera.setStyleSheet("QComboBox::down-arrow:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;padding-left:30px;\n"
"}\n"
"")
        self.comboBox_camera.setObjectName("comboBox_camera")
        self.comboBox_camera.addItem("")
        self.comboBox_camera.addItem("")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(3)
        # self.label_4.setStyleSheet("background-color: rgb(75, 0, 130);")
        self.label_4.setMinimumSize(QtCore.QSize(80, 150))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3.raise_()
        self.begin.raise_()
        self.face.raise_()
        self.splitter.raise_()
        self.layoutWidget.raise_()
        self.eye.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        intelligentwheelchair.setCentralWidget(self.centralwidget)
        '''self.menubar = QtWidgets.QMenuBar(intelligentwheelchair)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")'''
        #intelligentwheelchair.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(intelligentwheelchair)
        self.statusbar.setObjectName("statusbar")
        intelligentwheelchair.setStatusBar(self.statusbar)
        self.actionsdsd = QtWidgets.QAction(intelligentwheelchair)
        self.actionsdsd.setObjectName("actionsdsd")
        #self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(intelligentwheelchair)
        QtCore.QMetaObject.connectSlotsByName(intelligentwheelchair)

    def retranslateUi(self, intelligentwheelchair):
        _translate = QtCore.QCoreApplication.translate
        intelligentwheelchair.setWindowTitle(_translate("intelligentwheelchair", "智能眼动轮椅控制平台"))
        self.begin.setText(_translate("intelligentwheelchair", "启动"))
        self.label.setText(_translate("intelligentwheelchair", "人眼提取"))
        self.label_5.setText(_translate("intelligentwheelchair", "         数据采集区"))
        self.label_6.setText(_translate("intelligentwheelchair", "人脸图像"))
        self.label_7.setText(_translate("intelligentwheelchair", "               轮椅控制区"))
        self.camera_word.setText(_translate("intelligentwheelchair", " 摄像头编号"))
        self.comboBox_camera.setItemText(0, _translate("intelligentwheelchair", "0"))
        self.comboBox_camera.setItemText(1, _translate("intelligentwheelchair", "1"))
        #self.menu.setTitle(_translate("intelligentwheelchair", "人工智能和机器人实验室"))
        self.actionsdsd.setText(_translate("intelligentwheelchair", "sdsd "))
import source_pyqt_rc
